### ISSUE TITLE
CSV changed again

### ISSUE THREAD

**Issue by tbm** [siddhantgoel/beancount-dkb#146]
It looks like the CSV changed yet again!

The first line is empty now.  It doesn't mention the type of account anymore.

And I get:

```
    return line["Betrag"].rstrip(" €")
           ~~~~^^^^^^^^^^
KeyError: 'Betrag'
```

It appears to be called `Betrag (€)` now.

**Comment by tbm** [comment]
This is for EC (and Tageskonto), which is the same.

This is the format:

```

""
"Kontostand vom 02.01.2024:";"25,00 EUR"
""
"Buchungsdatum";"Wertstellung";"Status";"Zahlungspflichtige*r";"Zahlungsempfänger*in";"Verwendungszweck";"Umsatztyp";"IBAN";"Betrag (€)";"Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz"
```

(first line is blank)

**Comment by siddhantgoel** [comment]
I think this is the same issue as mentioned in the comment here: https://github.com/siddhantgoel/beancount-dkb/issues/123#issuecomment-1858800769.

I'll close this issue accordingly so we can track all these format changes in one place. Feel free to reopen if you feel this should be a different issue.

**Comment by tbm** [comment]
Sorry for filing a duplicate.  I thought this was different because I only got this new CSV now and not a few weeks ago (whereas the other bug report is monthly old).  But I guess what changed is the web access. Thanks.
