### ISSUE TITLE
Ugly sed hack to use changed CSV file with v0.19

### ISSUE THREAD

**Issue by momu** [siddhantgoel/beancount-dkb#191]
I struggled a bit as I figured out that the old banking and its export is finally gone. Beancount v3 lacks the `fava` support or vice versa, so I had to find a easy solution to import the current CSV files. 

The problem is, that the EC importer expects `;` as separator but `,` is used. I was not successful altering the code on the first try so the following `sed` call does the trick (just replacing `","` with `";"`). Hope this helps.

`sed -i 's/","/";"/g' 13-10-2024_Umsatzliste_Girokonto_DE04120300001122334455.csv`

**Comment by siddhantgoel** [comment]
Hey, which version of the importer are you using? DKB switched to using `,` as the separator in their new online banking but the importer should support that without any changes. 🤔 I just imported my September transactions without any modifications.

**Comment by momu** [comment]
That are the versions I'm using. But nevermind, works for me and actually should be easy to setup a second `venv` with beancount `v3` and recent `beancount-dkb` for importing and using the old `venv` for having `fava` compatible with beancount `v2`.

```
$ pip show beancount-dkb
Name: beancount-dkb
Version: 0.19.0
```
```
$ pip show beancount
Name: beancount
Version: 2.3.6
Summary: Command-line Double-Entry Accounting
```
