### ISSUE TITLE
Credit Card Saldo number format

### ISSUE THREAD

**Issue by FredWanninger** [siddhantgoel/beancount-dkb#84]
Hi,

when I export Credit Card stuff to CSV at my DKB account, the "Saldo" information (in the header) seems to have a different format, than your importer expects it to be.
https://github.com/siddhantgoel/beancount-dkb/blob/469d195029346e66ddde072d286e00e26599e822/beancount_dkb/credit.py#L117-L120
For me, the number in the CSV is already in a machine-readable format (e.g. 4664.87), and does not have to be converted. Could you please check this?

Thanks and Regards
Fred

**Comment by three-comrades** [comment]
I observed the same behavior: for some reason, the Saldo uses '.' as a decimal separator, while all the other numbers use ',' as a decimal separator.

**Comment by siddhantgoel** [comment]
I just pushed `v0.7.1` to PyPI. Could you please update and check if this resolves the issue?

**Comment by three-comrades** [comment]
The git version works for me. Thanks a lot!

**Comment by FredWanninger** [comment]
works for me. Thanks!
